name: FOSSA
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: FOSSA analysis
      run: |
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash -s -- -b .
        ./fossa init
        ./fossa analyze
      env:
        FOSSA_API_KEY: ${{ secrets.fossa_api_key }}
